#!/usr/bin/bash
# 20/09/2019, Lottomatica
# Alessio Dini
# Estrae tutti gli host di tipo vmware registrati su Satellite. Dalla lista esclude tutte gli host che nel nome hanno *capsule*
# Utile per la domanda "quante guest sono registrate su Satellite?"

cat << EOF > /tmp/hammer_no_timeout.yml
:foreman:
  :request_timeout: -1
EOF

ORA=$(date +"%d_%m_%Y")
FILE=guest_vmware_$ORA.log
hammer -c /tmp/hammer_no_timeout.yml fact list --search "fact=virt::host_type and value=vmware" | grep vmware | awk '{ print $1 }' | sort | uniq | grep -vi capsule > $FILE
TOTALE=$(wc -l guest_vmware_$ORA.log | awk '{ print $1 }')
echo -n "Estrazione di $TOTALE guest, il file si chiama $FILE"
echo
